In [5]:
import pandas as pd

In [2]:
npi_df = pd.read_csv("https://s3-us-west-1.amazonaws.com/physician-referral-graph/npidata_pfile_20050523-20180408_withHeader.csv", nrows=100)

In [3]:
npi_df.head()

,NPI,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,...,Healthcare Provider Taxonomy Group_6,Healthcare Provider Taxonomy Group_7,Healthcare Provider Taxonomy Group_8,Healthcare Provider Taxonomy Group_9,Healthcare Provider Taxonomy Group_10,Healthcare Provider Taxonomy Group_11,Healthcare Provider Taxonomy Group_12,Healthcare Provider Taxonomy Group_13,Healthcare Provider Taxonomy Group_14,Healthcare Provider Taxonomy Group_15
0,1679576722,1.0,NaN,NaN,NaN,WIEBE,DAVID,A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1588667638,1.0,NaN,NaN,NaN,PILCHER,WILLIAM,C,DR.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1497758544,2.0,NaN,<UNAVAIL>,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1306849450,1.0,NaN,NaN,NaN,SMITSON,HAROLD,LEROY,DR.,II,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1215930367,1.0,NaN,NaN,NaN,GRESSOT,LAURENT,NaN,DR.,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
npi_df.set_index(['NPI'], inplace=True)

In [5]:
npi_df.head()

,Entity Type Code,Replacement NPI,Employer Identification Number (EIN),Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Name Prefix Text,Provider Name Suffix Text,Provider Credential Text,...,Healthcare Provider Taxonomy Group_6,Healthcare Provider Taxonomy Group_7,Healthcare Provider Taxonomy Group_8,Healthcare Provider Taxonomy Group_9,Healthcare Provider Taxonomy Group_10,Healthcare Provider Taxonomy Group_11,Healthcare Provider Taxonomy Group_12,Healthcare Provider Taxonomy Group_13,Healthcare Provider Taxonomy Group_14,Healthcare Provider Taxonomy Group_15
NPI,,,,,,,,,,,,,,,,,,,,,
1679576722,1.0,NaN,NaN,NaN,WIEBE,DAVID,A,NaN,NaN,M.D.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1588667638,1.0,NaN,NaN,NaN,PILCHER,WILLIAM,C,DR.,NaN,MD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1497758544,2.0,NaN,<UNAVAIL>,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1306849450,1.0,NaN,NaN,NaN,SMITSON,HAROLD,LEROY,DR.,II,M.D.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1215930367,1.0,NaN,NaN,NaN,GRESSOT,LAURENT,NaN,DR.,NaN,M.D.,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
npi_df['Provider Business Practice Location Address Postal Code']

KeyError: 'Provider Business Practice Location Address Postal Code'

In [6]:
for col in npi_df.columns:
    print(col)

 Entity Type Code
 Replacement NPI
 Employer Identification Number (EIN)
 Provider Organization Name (Legal Business Name)
 Provider Last Name (Legal Name)
 Provider First Name
 Provider Middle Name
 Provider Name Prefix Text
 Provider Name Suffix Text
 Provider Credential Text
 Provider Other Organization Name
 Provider Other Organization Name Type Code
 Provider Other Last Name
 Provider Other First Name
 Provider Other Middle Name
 Provider Other Name Prefix Text
 Provider Other Name Suffix Text
 Provider Other Credential Text
 Provider Other Last Name Type Code
 Provider First Line Business Mailing Address
 Provider Second Line Business Mailing Address
 Provider Business Mailing Address City Name
 Provider Business Mailing Address State Name
 Provider Business Mailing Address Postal Code
 Provider Business Mailing Address Country Code (If outside US)
 Provider Business Mailing Address Telephone Number
 Provider Business Mailing Address Fax Number
 Provider First Line Business Practice Location Address
 Provider Second Line Business Practice Location Address
 Provider Business Practice Location Address City Name
 Provider Business Practice Location Address State Name
 Provider Business Practice Location Address Postal Code
 Provider Business Practice Location Address Country Code (If outside US)
 Provider Business Practice Location Address Telephone Number
 Provider Business Practice Location Address Fax Number
 Provider Enumeration Date
 Last Update Date
 NPI Deactivation Reason Code
 NPI Deactivation Date
 NPI Reactivation Date
 Provider Gender Code
 Authorized Official Last Name
 Authorized Official First Name
 Authorized Official Middle Name
 Authorized Official Title or Position
 Authorized Official Telephone Number
 Healthcare Provider Taxonomy Code_1
 Provider License Number_1
 Provider License Number State Code_1
 Healthcare Provider Primary Taxonomy Switch_1
 Healthcare Provider Taxonomy Code_2
 Provider License Number_2
 Provider License Number State Code_2
 Healthcare Provider Primary Taxonomy Switch_2
 Healthcare Provider Taxonomy Code_3
 Provider License Number_3
 Provider License Number State Code_3
 Healthcare Provider Primary Taxonomy Switch_3
 Healthcare Provider Taxonomy Code_4
 Provider License Number_4
 Provider License Number State Code_4
 Healthcare Provider Primary Taxonomy Switch_4
 Healthcare Provider Taxonomy Code_5
 Provider License Number_5
 Provider License Number State Code_5
 Healthcare Provider Primary Taxonomy Switch_5
 Healthcare Provider Taxonomy Code_6
 Provider License Number_6
 Provider License Number State Code_6
 Healthcare Provider Primary Taxonomy Switch_6
 Healthcare Provider Taxonomy Code_7
 Provider License Number_7
 Provider License Number State Code_7
 Healthcare Provider Primary Taxonomy Switch_7
 Healthcare Provider Taxonomy Code_8
 Provider License Number_8
 Provider License Number State Code_8
 Healthcare Provider Primary Taxonomy Switch_8
 Healthcare Provider Taxonomy Code_9
 Provider License Number_9
 Provider License Number State Code_9
 Healthcare Provider Primary Taxonomy Switch_9
 Healthcare Provider Taxonomy Code_10
 Provider License Number_10
 Provider License Number State Code_10
 Healthcare Provider Primary Taxonomy Switch_10
 Healthcare Provider Taxonomy Code_11
 Provider License Number_11
 Provider License Number State Code_11
 Healthcare Provider Primary Taxonomy Switch_11
 Healthcare Provider Taxonomy Code_12
 Provider License Number_12
 Provider License Number State Code_12
 Healthcare Provider Primary Taxonomy Switch_12
 Healthcare Provider Taxonomy Code_13
 Provider License Number_13
 Provider License Number State Code_13
 Healthcare Provider Primary Taxonomy Switch_13
 Healthcare Provider Taxonomy Code_14
 Provider License Number_14
 Provider License Number State Code_14
 Healthcare Provider Primary Taxonomy Switch_14
 Healthcare Provider Taxonomy Code_15
 Provider License Number_15
 Provider License Number State Code_15
 Healthcare Provider Primary Taxonomy Switch_15
 Other Provider Identifier_1
 Other Provider Identifier Type Code_1
 Other Provider Identifier State_1
 Other Provider Identifier Issuer_1
 Other Provider Identifier_2
 Other Provider Identifier Type Code_2
 Other Provider Identifier State_2
 Other Provider Identifier Issuer_2
 Other Provider Identifier_3
 Other Provider Identifier Type Code_3
 Other Provider Identifier State_3
 Other Provider Identifier Issuer_3
 Other Provider Identifier_4
 Other Provider Identifier Type Code_4
 Other Provider Identifier State_4
 Other Provider Identifier Issuer_4
 Other Provider Identifier_5
 Other Provider Identifier Type Code_5
 Other Provider Identifier State_5
 Other Provider Identifier Issuer_5
 Other Provider Identifier_6
 Other Provider Identifier Type Code_6
 Other Provider Identifier State_6
 Other Provider Identifier Issuer_6
 Other Provider Identifier_7
 Other Provider Identifier Type Code_7
 Other Provider Identifier State_7
 Other Provider Identifier Issuer_7
 Other Provider Identifier_8
 Other Provider Identifier Type Code_8
 Other Provider Identifier State_8
 Other Provider Identifier Issuer_8
 Other Provider Identifier_9
 Other Provider Identifier Type Code_9
 Other Provider Identifier State_9
 Other Provider Identifier Issuer_9
 Other Provider Identifier_10
 Other Provider Identifier Type Code_10
 Other Provider Identifier State_10
 Other Provider Identifier Issuer_10
 Other Provider Identifier_11
 Other Provider Identifier Type Code_11
 Other Provider Identifier State_11
 Other Provider Identifier Issuer_11
 Other Provider Identifier_12
 Other Provider Identifier Type Code_12
 Other Provider Identifier State_12
 Other Provider Identifier Issuer_12
 Other Provider Identifier_13
 Other Provider Identifier Type Code_13
 Other Provider Identifier State_13
 Other Provider Identifier Issuer_13
 Other Provider Identifier_14
 Other Provider Identifier Type Code_14
 Other Provider Identifier State_14
 Other Provider Identifier Issuer_14
 Other Provider Identifier_15
 Other Provider Identifier Type Code_15
 Other Provider Identifier State_15
 Other Provider Identifier Issuer_15
 Other Provider Identifier_16
 Other Provider Identifier Type Code_16
 Other Provider Identifier State_16
 Other Provider Identifier Issuer_16
 Other Provider Identifier_17
 Other Provider Identifier Type Code_17
 Other Provider Identifier State_17
 Other Provider Identifier Issuer_17
 Other Provider Identifier_18
 Other Provider Identifier Type Code_18
 Other Provider Identifier State_18
 Other Provider Identifier Issuer_18
 Other Provider Identifier_19
 Other Provider Identifier Type Code_19
 Other Provider Identifier State_19
 Other Provider Identifier Issuer_19
 Other Provider Identifier_20
 Other Provider Identifier Type Code_20
 Other Provider Identifier State_20
 Other Provider Identifier Issuer_20
 Other Provider Identifier_21
 Other Provider Identifier Type Code_21
 Other Provider Identifier State_21
 Other Provider Identifier Issuer_21
 Other Provider Identifier_22
 Other Provider Identifier Type Code_22
 Other Provider Identifier State_22
 Other Provider Identifier Issuer_22
 Other Provider Identifier_23
 Other Provider Identifier Type Code_23
 Other Provider Identifier State_23
 Other Provider Identifier Issuer_23
 Other Provider Identifier_24
 Other Provider Identifier Type Code_24
 Other Provider Identifier State_24
 Other Provider Identifier Issuer_24
 Other Provider Identifier_25
 Other Provider Identifier Type Code_25
 Other Provider Identifier State_25
 Other Provider Identifier Issuer_25
 Other Provider Identifier_26
 Other Provider Identifier Type Code_26
 Other Provider Identifier State_26
 Other Provider Identifier Issuer_26
 Other Provider Identifier_27
 Other Provider Identifier Type Code_27
 Other Provider Identifier State_27
 Other Provider Identifier Issuer_27
 Other Provider Identifier_28
 Other Provider Identifier Type Code_28
 Other Provider Identifier State_28
 Other Provider Identifier Issuer_28
 Other Provider Identifier_29
 Other Provider Identifier Type Code_29
 Other Provider Identifier State_29
 Other Provider Identifier Issuer_29
 Other Provider Identifier_30
 Other Provider Identifier Type Code_30
 Other Provider Identifier State_30
 Other Provider Identifier Issuer_30
 Other Provider Identifier_31
 Other Provider Identifier Type Code_31
 Other Provider Identifier State_31
 Other Provider Identifier Issuer_31
 Other Provider Identifier_32
 Other Provider Identifier Type Code_32
 Other Provider Identifier State_32
 Other Provider Identifier Issuer_32
 Other Provider Identifier_33
 Other Provider Identifier Type Code_33
 Other Provider Identifier State_33
 Other Provider Identifier Issuer_33
 Other Provider Identifier_34
 Other Provider Identifier Type Code_34
 Other Provider Identifier State_34
 Other Provider Identifier Issuer_34
 Other Provider Identifier_35
 Other Provider Identifier Type Code_35
 Other Provider Identifier State_35
 Other Provider Identifier Issuer_35
 Other Provider Identifier_36
 Other Provider Identifier Type Code_36
 Other Provider Identifier State_36
 Other Provider Identifier Issuer_36
 Other Provider Identifier_37
 Other Provider Identifier Type Code_37
 Other Provider Identifier State_37
 Other Provider Identifier Issuer_37
 Other Provider Identifier_38
 Other Provider Identifier Type Code_38
 Other Provider Identifier State_38
 Other Provider Identifier Issuer_38
 Other Provider Identifier_39
 Other Provider Identifier Type Code_39
 Other Provider Identifier State_39
 Other Provider Identifier Issuer_39
 Other Provider Identifier_40
 Other Provider Identifier Type Code_40
 Other Provider Identifier State_40
 Other Provider Identifier Issuer_40
 Other Provider Identifier_41
 Other Provider Identifier Type Code_41
 Other Provider Identifier State_41
 Other Provider Identifier Issuer_41
 Other Provider Identifier_42
 Other Provider Identifier Type Code_42
 Other Provider Identifier State_42
 Other Provider Identifier Issuer_42
 Other Provider Identifier_43
 Other Provider Identifier Type Code_43
 Other Provider Identifier State_43
 Other Provider Identifier Issuer_43
 Other Provider Identifier_44
 Other Provider Identifier Type Code_44
 Other Provider Identifier State_44
 Other Provider Identifier Issuer_44
 Other Provider Identifier_45
 Other Provider Identifier Type Code_45
 Other Provider Identifier State_45
 Other Provider Identifier Issuer_45
 Other Provider Identifier_46
 Other Provider Identifier Type Code_46
 Other Provider Identifier State_46
 Other Provider Identifier Issuer_46
 Other Provider Identifier_47
 Other Provider Identifier Type Code_47
 Other Provider Identifier State_47
 Other Provider Identifier Issuer_47
 Other Provider Identifier_48
 Other Provider Identifier Type Code_48
 Other Provider Identifier State_48
 Other Provider Identifier Issuer_48
 Other Provider Identifier_49
 Other Provider Identifier Type Code_49
 Other Provider Identifier State_49
 Other Provider Identifier Issuer_49
 Other Provider Identifier_50
 Other Provider Identifier Type Code_50
 Other Provider Identifier State_50
 Other Provider Identifier Issuer_50
 Is Sole Proprietor
 Is Organization Subpart
 Parent Organization LBN
 Parent Organization TIN
 Authorized Official Name Prefix Text
 Authorized Official Name Suffix Text
 Authorized Official Credential Text
 Healthcare Provider Taxonomy Group_1
 Healthcare Provider Taxonomy Group_2
 Healthcare Provider Taxonomy Group_3
 Healthcare Provider Taxonomy Group_4
 Healthcare Provider Taxonomy Group_5
 Healthcare Provider Taxonomy Group_6
 Healthcare Provider Taxonomy Group_7
 Healthcare Provider Taxonomy Group_8
 Healthcare Provider Taxonomy Group_9
 Healthcare Provider Taxonomy Group_10
 Healthcare Provider Taxonomy Group_11
 Healthcare Provider Taxonomy Group_12
 Healthcare Provider Taxonomy Group_13
 Healthcare Provider Taxonomy Group_14
 Healthcare Provider Taxonomy Group_15

In [19]:
npi_df.columns = npi_df.columns.str.strip()

In [23]:
print(npi_df.columns.str.strip())

Index(['Entity Type Code', 'Replacement NPI',
       'Employer Identification Number (EIN)',
       'Provider Organization Name (Legal Business Name)',
       'Provider Last Name (Legal Name)', 'Provider First Name',
       'Provider Middle Name', 'Provider Name Prefix Text',
       'Provider Name Suffix Text', 'Provider Credential Text',
       ...
       'Healthcare Provider Taxonomy Group_6',
       'Healthcare Provider Taxonomy Group_7',
       'Healthcare Provider Taxonomy Group_8',
       'Healthcare Provider Taxonomy Group_9',
       'Healthcare Provider Taxonomy Group_10',
       'Healthcare Provider Taxonomy Group_11',
       'Healthcare Provider Taxonomy Group_12',
       'Healthcare Provider Taxonomy Group_13',
       'Healthcare Provider Taxonomy Group_14',
       'Healthcare Provider Taxonomy Group_15'],
      dtype='object', length=328)

In [25]:
x = pd.Series(['Entity Type Code', 'Replacement NPI',
       'Employer Identification Number (EIN)',
       'Provider Organization Name (Legal Business Name)',
       'Provider Last Name (Legal Name)', 'Provider First Name',
       'Provider Middle Name', 'Provider Name Prefix Text',
       'Provider Name Suffix Text', 'Provider Credential Text',
       'Healthcare Provider Taxonomy Group_6',
       'Healthcare Provider Taxonomy Group_7',
       'Healthcare Provider Taxonomy Group_8',
       'Healthcare Provider Taxonomy Group_9',
       'Healthcare Provider Taxonomy Group_10',
       'Healthcare Provider Taxonomy Group_11',
       'Healthcare Provider Taxonomy Group_12',
       'Healthcare Provider Taxonomy Group_13',
       'Healthcare Provider Taxonomy Group_14',
       'Healthcare Provider Taxonomy Group_15'])

In [26]:
x.str.strip()

0                                     Entity Type Code
1                                      Replacement NPI
2                 Employer Identification Number (EIN)
3     Provider Organization Name (Legal Business Name)
4                      Provider Last Name (Legal Name)
5                                  Provider First Name
6                                 Provider Middle Name
7                            Provider Name Prefix Text
8                            Provider Name Suffix Text
9                             Provider Credential Text
10                Healthcare Provider Taxonomy Group_6
11                Healthcare Provider Taxonomy Group_7
12                Healthcare Provider Taxonomy Group_8
13                Healthcare Provider Taxonomy Group_9
14               Healthcare Provider Taxonomy Group_10
15               Healthcare Provider Taxonomy Group_11
16               Healthcare Provider Taxonomy Group_12
17               Healthcare Provider Taxonomy Group_13
18               Healthcare Provider Taxonomy Group_14
19               Healthcare Provider Taxonomy Group_15
dtype: object

In [16]:
new_npi_df.head()

          NPI
0  1679576722
1  1588667638
2  1497758544
3  1306849450
4  1215930367

In [27]:
new_npi_df = pd.read_csv('../data/samples/npidata_pfile_20050523-20180408-subsample.csv', usecols=['NPI', ' Provider Organization Name (Legal Business Name)'])

In [28]:
new_npi_df.head()

          NPI  Provider Organization Name (Legal Business Name)
0  1679576722                                               NaN
1  1588667638                                               NaN
2  1497758544            CUMBERLAND COUNTY HOSPITAL SYSTEM, INC
3  1306849450                                               NaN
4  1215930367                                               NaN

In [1]:
usecols=['NPI','Provider Organization Name (Legal Business Name)','Provider Business Practice Location Address City Name','Provider Business Practice Location Address State Name','Provider Business Practice Location Address Country Code (If outside US)','Provider Gender Code','Healthcare Provider Taxonomy Code_1','Is Sole Proprietor']

In [2]:
npi_categorical_cols = ['Provider Organization Name (Legal Business Name)','Provider Business Practice Location Address City Name','Provider Business Practice Location Address State Name','Provider Business Practice Location Address Country Code (If outside US)','Provider Gender Code','Is Sole Proprietor']

In [3]:
npi_usecols = ['NPI','Provider Organization Name (Legal Business Name)','Provider Business Practice Location Address City Name','Provider Business Practice Location Address State Name','Provider Business Practice Location Address Country Code (If outside US)','Provider Gender Code','Healthcare Provider Taxonomy Code_1','Is Sole Proprietor']

In [6]:
npi_df = pd.read_csv("https://s3-us-west-1.amazonaws.com/physician-referral-graph/npidata_pfile_20050523-20180408_withHeader.csv", index_col=['NPI'], usecols=npi_usecols)

/home/ubuntu/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:466: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [7]:
npi_df

,Provider Organization Name (Legal Business Name),Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Business Practice Location Address Country Code (If outside US),Provider Gender Code,Healthcare Provider Taxonomy Code_1,Is Sole Proprietor
NPI,,,,,,,
1679576722,NaN,KEARNEY,NE,US,M,207X00000X,X
1588667638,NaN,JACKSONVILLE,FL,US,M,207RC0000X,N
1497758544,"CUMBERLAND COUNTY HOSPITAL SYSTEM, INC",FAYETTEVILLE,NC,US,NaN,251G00000X,NaN
1306849450,NaN,ATHENS,TX,US,M,2085R0202X,N
1215930367,NaN,HOUSTON,TX,US,M,174400000X,N
1023011178,COLLABRIA CARE,NAPA,CA,US,NaN,251G00000X,NaN
1932102084,NaN,TOLEDO,OH,US,M,207RC0000X,N
1841293990,NaN,NEW YORK,NY,US,F,231H00000X,N
1750384806,NaN,LUBBOCK,TX,US,M,207R00000X,N
1669475711,NaN,SUGAR LAND,TX,US,F,208000000X,Y
1578566626,NaN,PHOENIX,AZ,US,M,207Q00000X,N
1487657532,NaN,NORMAN,OK,US,F,207V00000X,N
1396748448,NaN,LIVERPOOL,NY,US,F,363A00000X,N
1205839354,NaN,O FALLON,MO,US,M,207X00000X,N
1114920261,NaN,TALLAHASSEE,FL,US,M,207R00000X,N
1023011079,"ADVANTAGE HOME HEALTH CARE, INC.",MORRIS,IL,US,NaN,251E00000X,NaN
1932102985,NaN,ATHENS,OH,US,M,207Q00000X,N
1841293891,NaN,CROSSVILLE,TN,US,M,208G00000X,Y
1750384707,NaN,MINNEAPOLIS,MN,US,M,174400000X,N
1669475612,NaN,LAS VEGAS,NV,US,F,363LW0102X,N
1578566527,NaN,MARIETTA,GA,US,M,207X00000X,N
1487657433,"PEKIN MRI, LLC",PEKIN,IL,US,NaN,293D00000X,NaN
1396748349,NaN,HOUSTON,TX,US,M,207VE0102X,N
1205839255,NaN,GREAT NECK,NY,US,M,207RC0000X,N
1114920162,NaN,TARBORO,NC,US,M,208000000X,N
1922001973,NaN,ALBERT LEA,MN,US,F,1041C0700X,X
1831192889,NaN,DOTHAN,AL,US,M,207R00000X,X
1740283795,EASTERN STAR MASONIC HOME,BOONE,IA,US,NaN,311Z00000X,NaN
1659374601,NaN,KINGSPORT,TN,US,F,207Q00000X,Y
1568465516,NaN,SUFFERN,NY,US,M,208G00000X,N
...,...,...,...,...,...,...,...
1134626070,NaN,ALBUQUERQUE,NM,US,M,390200000X,N
1952808891,NaN,FRESNO,CA,US,F,390200000X,N
1295232148,NaN,SAN JOSE,CA,US,M,390200000X,N
1922505874,NaN,NEW YORK,NY,US,F,390200000X,Y
1740787696,NaN,LAS VEGAS,NV,US,F,106S00000X,Y
1659878502,NaN,NEWARK,NJ,US,M,390200000X,N
1386141232,NaN,LOS ANGELES,CA,US,M,101Y00000X,Y
1003313958,NaN,ORLANDO,FL,US,M,225200000X,N
1821595778,NaN,CLINTON TOWNSHIP,MI,US,M,2251N0400X,N
1730686684,NaN,LOUISVILLE,KY,US,F,390200000X,N
1558868406,NaN,BROOKLYN,NY,US,F,103TS0200X,N
1811494768,"ATTAIN AUTISM SERVICES, LLC",FORT COLLINS,CO,US,NaN,103K00000X,NaN
1639676588,NaN,TOWSON,MD,US,F,390200000X,Y
1184121030,NaN,OAK LAWN,IL,US,F,390200000X,N
1629575576,NaN,MILWAUKEE,WI,US,F,390200000X,N
1356848204,NaN,BOSTON,MA,US,F,390200000X,N
1174020028,NaN,STANFORD,CA,US,M,390200000X,N
1891292744,NaN,ATLANTA,GA,US,M,390200000X,N
1528565470,NaN,BIRMINGHAM,AL,US,M,390200000X,N
1346747292,NaN,PHILADELPHIA,PA,US,M,390200000X,N
1700383668,NaN,TULSA,OK,US,M,390200000X,N
1255838116,NaN,WINSTON-SALEM,NC,US,M,390200000X,N
1164929022,NaN,PALO ALTO,CA,US,F,390200000X,N
1790282655,NaN,BIRMINGHAM,AL,US,F,390200000X,N
1699272559,NaN,MUSKOGEE,OK,US,M,224Y00000X,N
1417454372,NaN,WORCESTER,MA,US,F,390200000X,N
1235636192,NaN,JACKSONVILLE,FL,US,F,363LF0000X,Y
1053818914,NaN,PHILADELPHIA,PA,US,F,103TC0700X,Y
1962909820,NaN,NEW YORK,NY,US,F,103TC0700X,Y
1871090738,NaN,DUNCANVILLE,TX,US,F,225200000X,N

In [8]:
len(npi_usecols)

8

In [12]:
npi_df['Provider Business Practice Location Address City Name'].value_counts()

NEW YORK            76404
HOUSTON             53319
BROOKLYN            51423
CHICAGO             50568
LOS ANGELES         48780
MIAMI               36403
PORTLAND            35414
PHILADELPHIA        34557
WASHINGTON          33053
SAN DIEGO           32164
LAS VEGAS           30735
DALLAS              29718
SEATTLE             29304
COLUMBUS            28989
SAN FRANCISCO       28593
BOSTON              27982
BALTIMORE           26878
BRONX               26855
PHOENIX             25934
SAN ANTONIO         25523
ROCHESTER           25128
ATLANTA             22471
SAINT LOUIS         21843
SPRINGFIELD         21763
PITTSBURGH          21731
INDIANAPOLIS        20536
CINCINNATI          20103
JACKSONVILLE        20076
CLEVELAND           20021
DENVER              19434
                    ...
LEGGETT                 1
TARCNTUM                1
ALYODONES               1
MARCOLA                 1
ARECBIBO                1
EATON CENTER            1
POUGH.                  1
SECUCUS                 1
LA GRANGEVILLE          1
BRAMBELTON              1
DOWNER GROVE            1
KING PARK               1
FOUNTAIN VLY            1
WOOD CROSS              1
MINDEN CITY             1
TAMVNING                1
PENN                    1
ANENTURA                1
ELLIOTTVILLE            1
BALWIN                  1
TUNTUTLIAK              1
GLENDALE SPRINGS        1
LINCOLWOOD              1
BURR RUDGE              1
HATOREY                 1
WHITTLER                1
OKABENA                 1
AMILTY                  1
FT. BRANCH              1
CULDESAC                1
Name: Provider Business Practice Location Address City Name, Length: 25156, dtype: int64